### ISSUE TITLE
Show the current Constituents document

### ISSUE THREAD

**Issue by liam4** [MrSherlockHolmes/New-Dock#1]
> Note: This is NOT the current Constituents document, and simply is a version in markdown, which may become the standard, if it works well.

Issue reporters (here on GitHub) right now could make a report about consituents/main.md, but the issue may have been fixed in the "development" version of the document.

Or, alternatively, there could be a "has patch" issue tag, to describe issues that have patches but haven't had the version they're patched in published yet..

**Comment by liam4** [comment]
Having the real document be public makes it easier for pull-requesters for typos and such as well!

**Comment by MrSherlockHolmes** [comment]
The *previous* current constituents document was "main.txt", but, as you have mentioned, I will now make main.md the current one. Thanks
